// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5M_tTvDyBdNrZCco236k3JKRZOkf03s',
    appId: '1:104590120247:web:30e3932600d8649847f6b2',
    messagingSenderId: '104590120247',
    projectId: 'studynsync-99bb5',
    authDomain: 'studynsync-99bb5.firebaseapp.com',
    storageBucket: 'studynsync-99bb5.firebasestorage.app',
    measurementId: 'G-7J8RWZ5N8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZK-C_M4Dqtvc8lPDJmUL4CF37T9WfW8',
    appId: '1:104590120247:android:bb67bfa2293b6e4747f6b2',
    messagingSenderId: '104590120247',
    projectId: 'studynsync-99bb5',
    storageBucket: 'studynsync-99bb5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh5M_tTvDyBdNrZCco236k3JKRZOkf03s',
    appId: '1:104590120247:web:d6a30ffa9f615e7747f6b2',
    messagingSenderId: '104590120247',
    projectId: 'studynsync-99bb5',
    authDomain: 'studynsync-99bb5.firebaseapp.com',
    storageBucket: 'studynsync-99bb5.firebasestorage.app',
    measurementId: 'G-ENSCKLG14T',
  );
}
